module.exports = [
  "Acil Durum ve Afet Yönetimi",
  "Adalet",
  "Adalet Meslek Yüksekokulu",
  "Adli Bilişim Mühendisliği",
  "Ağaç İşleri Endüstri Mühendisliği",
  "Ağız ve Diş Sağlığı",
  "Aile ve Tüketici Bilimleri",
  "Aktüerya Bilimleri",
  "Aktüerya ve Risk Yönetimi",
  "Alman Dili ve Edebiyatı",
  "Almanca Öğretmenliği",
  "Alternatif Enerji Kaynakları Teknolojisi",
  "Ameliyathane Hizmetleri",
  "Anestezi",
  "Anestezi",
  "Anestezi",
  "Antrenörlük Eğitimi",
  "Antropoloji",
  "Arap Dili ve Edebiyatı",
  "Arapça Öğretmenliği",
  "Arıcılık",
  "Arkeoloji",
  "Arnavut Dili ve Edebiyatı",
  "Astronomi ve Astrofizik",
  "Astronomi ve Uzay Bilimleri",
  "Aşçılık",
  "Atçılık ve Antrenörlüğü",
  "Atık Yönetimi",
  "Avcılık ve Yaban Hayatı",
  "Ayakkabı Tasarım ve Üretimi",
  "Ayakkabı Tasarımı ve Üretimi",
  "Azerbaycan Türkçesi ve Edebiyatı",
  "Bağcılık",
  "Bahçe Bitkileri",
  "Bahçe Tarımı",
  "Bahçe ve Tarla Bitkileri",
  "Balıkçılık Teknolojisi Mühendisliği",
  "Bankacılık ve Sigortacılık",
  "Basım Teknolojileri",
  "Basım ve Yayın Teknolojileri",
  "Basın ve Yayın",
  "Basın ve Yayıncılık",
  "Beden Eğitimi ve Spor Öğretmenliği",
  "Bilgi Güvenliği Teknolojisi",
  "Bilgi ve Belge Yönetimi",
  "Bilgi Yönetimi",
  "Bilgisayar Bilimleri",
  "Bilgisayar Destekli Tasarım ve Animasyon",
  "Bilgisayar Mühendisliği",
  "Bilgisayar Operatörlüğü",
  "Bilgisayar Programcılığı",
  "Bilgisayar Teknolojisi",
  "Bilgisayar ve Öğretim Teknolojileri Öğretmenliği",
  "Bilim Tarihi",
  "Bilişim Sistemleri Mühendisliği",
  "Bitki Koruma",
  "Bitki Koruma",
  "Bitkisel Üretim ve Teknolojileri",
  "Biyokimya",
  "Biyokimya",
  "Biyoloji",
  "Biyoloji Öğretmenliği",
  "Biyomedikal Cihaz Teknolojisi",
  "Biyomedikal Cihaz Teknolojisi",
  "Biyomedikal Mühendisliği",
  "Biyomühendislik",
  "Biyosistem Mühendisliği",
  "Biyoteknoloji",
  "Biyoteknoloji ve Moleküler Biyoloji",
  "Boşnak Dili ve Edebiyatı",
  "Boya Teknolojisi",
  "Büro Yönetimi ve Yönetici Asistanlığı",
  "Canlandırma Filmi Tasarım ve Yönetimi",
  "Cevher Hazırlama Mühendisliği",
  "Ceza İnfaz ve Güvenlik Hizmetleri",
  "Coğrafi Bilgi Sistemleri",
  "Coğrafya",
  "Coğrafya Öğretmenliği",
  "Çağdaş Türk Lehçeleri ve Edebiyatları",
  "Çağdaş Yunan Dili ve Edebiyatı",
  "Çağrı Merkezi Hizmetleri",
  "Çalışma Ekonomisi ve Endüstri İlişkileri",
  "Çay Tarımı ve İşleme Teknolojisi",
  "Çerkez Dili ve Edebiyatı",
  "Çevre Koruma ve Kontrol",
  "Çevre Mühendisliği",
  "Çevre Sağlığı",
  "Çevre Temizliği ve Denetimi",
  "Çim Alan Tesisi ve Yönetimi",
  "Çin Dili ve Edebiyatı",
  "Çini Sanatı ve Tasarımı",
  "Çocuk Gelişimi",
  "Çocuk Gelişimi",
  "Çocuk Koruma ve Bakım Hizmetleri",
  "Deniz Ulaştırma İşletme Mühendisliği",
  "Deniz Ulaştırma ve İşletme",
  "Deniz ve Liman İşletmeciliği",
  "Denizci Sağlığı",
  "Denizcilik İşletmeleri Yönetimi",
  "Deri Konfeksiyon",
  "Deri Mühendisliği",
  "Deri Teknolojisi",
  "Dezenfeksiyon, Sterilizasyon ve Antisepsi",
  "Dış Ticaret",
  "Dilbilim",
  "Dilbilimi",
  "Diş Hekimliği",
  "Diş Protez Teknolojisi",
  "Diyaliz",
  "Doğal Yapı Taşları Teknolojisi",
  "Doğalgaz ve Tesisatı Teknolojisi",
  "Döküm",
  "Eczacılık",
  "Eczane Hizmetleri",
  "Ekonometri",
  "Ekonomi",
  "Ekonomi ve Finans",
  "El Sanatları",
  "El Sanatları Tasarımı ve Üretimi",
  "Elektrik",
  "Elektrik Enerjisi Üretim, İletim ve Dağıtımı",
  "Elektrik Mühendisliği",
  "Elektrik-Elektronik Mühendisliği",
  "Elektrikli Cihaz Teknolojisi",
  "Elektronik Haberleşme Teknolojisi",
  "Elektronik Mühendisliği",
  "Elektronik Teknolojisi",
  "Elektronik ve Haberleşme Mühendisliği",
  "Elektronörofizyoloji",
  "Elektronörofizyoloji",
  "Emlak ve Emlak Yönetimi",
  "Endüstri Mühendisliği",
  "Endüstri Ürünleri Tasarımı",
  "Endüstriyel Cam ve Seramik",
  "Endüstriyel Kalıpçılık",
  "Endüstriyel Tasarım",
  "Endüstriyel Tasarım Mühendisliği",
  "Endüstriyel Tavukçuluk",
  "Enerji Sistemleri Mühendisliği",
  "Enerji Tesisleri İşletmeciliği",
  "Engelli Bakımı ve Rehabilitasyon",
  "Ermeni Dili ve Edebiyatı",
  "Eser Koruma",
  "Eski Yunan Dili ve Edebiyatı",
  "Et ve Ürünleri Teknolojisi",
  "Evde Hasta Bakımı",
  "Fars Dili ve Edebiyatı",
  "Felsefe",
  "Felsefe Grubu Öğretmenliği",
  "Fen Bilgisi Öğretmenliği",
  "Fındık Eksperliği",
  "Fidan Yetiştiriciliği",
  "Film Tasarım ve Yazarlık",
  "Film Tasarım ve Yönetmenliği",
  "Film Tasarımı",
  "Finans ve Bankacılık",
  "Fizik",
  "Fizik Mühendisliği",
  "Fizik Öğretmenliği",
  "Fizyoterapi",
  "Fotoğraf",
  "Fotoğraf ve Video",
  "Fotoğrafçılık ve Kameramanlık",
  "Fransız Dili ve Edebiyatı",
  "Fransızca Öğretmenliği",
  "Gaz ve Tesisatı Teknolojisi",
  "Gazetecilik",
  "Geleneksel El Sanatları",
  "Gemi İnşaatı",
  "Gemi İnşaatı ve Gemi Makineleri Mühendisliği",
  "Gemi Makineleri İşletme",
  "Gemi ve Deniz Teknolojisi Mühendisliği",
  "Genetik ve Biyomühendislik",
  "Geomatik Mühendisliği",
  "Geoteknik",
  "Gıda Kalite Kontrolü ve Analizi",
  "Gıda Mühendisliği",
  "Gıda Teknolojisi",
  "Gıda Teknolojisi",
  "Giyim Üretim Teknolojisi",
  "Görsel İletişim Tasarımı",
  "Grafik Tasarımı",
  "Grafik Tasarımı",
  "Gümrük İşletme",
  "Gürcü Dili ve Edebiyatı",
  "Halıcılık ve Kilimcilik",
  "Halkbilim",
  "Halkla İlişkiler ve Tanıtım",
  "Halkla İlişkiler ve Tanıtım",
  "Harita Mühendisliği",
  "Harita ve Kadastro",
  "Havacılık ve Uzay Mühendisliği",
  "Hayvansal Üretim",
  "Hayvansal Üretim ve Teknolojileri",
  "Hibrid ve Elektrikli Taşıtlar Teknolojisi",
  "Hidrojeoloji Mühendisliği",
  "Hindoloji",
  "Hititoloji",
  "Hukuk",
  "Hukuk Büro Yönetimi ve Sekreterliği",
  "Hungaroloji",
  "İbrani Dili ve Edebiyatı",
  "İç Mekan Tasarımı",
  "İç Mimarlık",
  "İç Mimarlık ve Çevre Tasarımı",
  "İklimlendirme ve Soğutma Teknolojisi",
  "İkram Hizmetleri",
  "İktisat",
  "İlahiyat",
  "İletişim Bilimleri",
  "İletişim Sanatları",
  "İletişim Tasarımı",
  "İletişim Tasarımı ve Medya",
  "İletişim Tasarımı ve Yönetimi",
  "İlk ve Acil Yardım",
  "İlköğretim Matematik Öğretmenliği",
  "İmalat Mühendisliği",
  "İngiliz Dili ve Edebiyatı",
  "İngilizce Öğretmenliği",
  "İnsan Kaynakları Yönetimi",
  "İnşaat Mühendisliği",
  "İnşaat Teknolojisi",
  "İnternet ve Ağ Teknolojileri",
  "İslam Bilimleri",
  "İslami İlimler",
  "İspanyol Dili ve Edebiyatı",
  "İstatistik",
  "İstatistik ve Bilgisayar Bilimleri",
  "İş Makineleri Operatörlüğü",
  "İş Sağlığı ve Güvenliği",
  "İş ve Uğraşı Terapisi",
  "İşletme",
  "İşletme Bilgi Yönetimi",
  "İşletme Enformatiği",
  "İşletme Yönetimi",
  "İtalyan Dili ve Edebiyatı",
  "Japon Dili ve Edebiyatı",
  "Japonca Öğretmenliği",
  "Jeofizik Mühendisliği",
  "Jeoloji Mühendisliği",
  "Kamu Yönetimi",
  "Kanatlı Hayvan Yetiştiriciliği",
  "Karşılaştırmalı Edebiyat",
  "Kaynak Teknolojisi",
  "Kazak Dili ve Edebiyatı",
  "Kentsel Tasarım ve Peyzaj Mimarlığı",
  "Kimya",
  "Kimya Mühendisliği",
  "Kimya Öğretmenliği",
  "Kimya Teknolojisi",
  "Kimya ve Süreç Mühendisliği",
  "Klasik Arkeoloji",
  "Kontrol ve Otomasyon Mühendisliği",
  "Kontrol ve Otomasyon Teknolojisi",
  "Kooperatifçilik",
  "Kore Dili ve Edebiyatı",
  "Kozmetik Teknolojisi",
  "Kurgu-Ses ve Görüntü Yönetimi",
  "Kuyumculuk ve Mücevher Tasarımı",
  "Kuyumculuk ve Mücevherat Tasarımı",
  "Kuyumculuk ve Takı Tasarımı",
  "Kültür Varlıklarını Koruma ve Onarım",
  "Kültür ve İletişim Bilimleri",
  "Kültürel Miras ve Turizm",
  "Kümes Hayvanları Yetiştiriciliği",
  "Kürt Dili ve Edebiyatı",
  "Laborant ve Veteriner Sağlık",
  "Laboratuvar Teknolojisi",
  "Lastik ve Plastik Teknolojisi",
  "Latin Dili ve Edebiyatı",
  "Leh Dili ve Edebiyatı",
  "Lif ve Polimer Mühendisliği",
  "Lojistik",
  "Maden Mühendisliği",
  "Maden Teknolojisi",
  "Makine",
  "Makine Mühendisliği",
  "Makine ve İmalat Mühendisliği",
  "Makine, Resim ve Konstrüksiyon",
  "Maliye",
  "Maliye",
  "Malzeme Bilimi ve Mühendisliği",
  "Malzeme Bilimi ve Nanoteknoloji Mühendisliği",
  "Mantarcılık",
  "Marina ve Yat İşletmeciliği",
  "Matematik",
  "Matematik Mühendisliği",
  "Matematik Öğretmenliği",
  "Matematik-Bilgisayar",
  "Medya ve İletişim",
  "Mekatronik",
  "Mekatronik Mühendisliği",
  "Menkul Kıymetler ve Sermaye Piyasası",
  "Metalurji",
  "Metalurji ve Malzeme Mühendisliği",
  "Meteoroloji Mühendisliği",
  "Meyve ve Sebze İşleme Teknolojisi",
  "Mimari Dekoratif Sanatlar",
  "Mimari Restorasyon",
  "Mimarlık",
  "Mobilya ve Dekorasyon",
  "Moda Tasarımı",
  "Moda ve Tekstil Tasarımı",
  "Moda Yönetimi",
  "Moleküler Biyoloji ve Genetik",
  "Muhasebe Bilgi Sistemleri",
  "Muhasebe ve Vergi Uygulamaları",
  "Müzecilik",
  "Nanobilim ve Nanoteknoloji",
  "Nüfus ve Vatandaşlık",
  "Nükleer Enerji Mühendisliği",
  "Nükleer Teknoloji ve Radyasyon Güvenliği",
  "Nükleer Tıp Teknikleri",
  "Odyometri",
  "Okul Öncesi Öğretmenliği",
  "Optisyenlik",
  "Organik Tarım",
  "Organik Tarım İşletmeciliği",
  "Orman Endüstrisi Mühendisliği",
  "Orman Mühendisliği",
  "Ormancılık ve Orman Ürünleri",
  "Ortopedik Protez ve Ortez",
  "Oto Boya ve Karoseri",
  "Otobüs Kaptanlığı",
  "Otomotiv Mühendisliği",
  "Otomotiv Teknolojisi",
  "Otopsi Yardımcılığı",
  "Özel Eğitim Öğretmenliği",
  "Özel Güvenlik ve Koruma",
  "Patoloji Laboratuvar Teknikleri",
  "Pazarlama",
  "Perakende Satış ve Mağaza Yönetimi",
  "Perfüzyon Teknikleri",
  "Petrol ve Doğalgaz Mühendisliği",
  "Peyzaj Mimarlığı",
  "Peyzaj ve Süs Bitkileri",
  "Podoloji",
  "Polimer Mühendisliği",
  "Polimer Teknolojisi",
  "Posta Hizmetleri",
  "Protohistorya ve Ön Asya Arkeolojisi",
  "Psikoloji",
  "Radyo ve Televizyon Programcılığı",
  "Radyo ve Televizyon Teknolojisi",
  "Radyo, Televizyon ve Sinema",
  "Radyoterapi",
  "Rafineri ve Petro-Kimya Teknolojisi",
  "Raylı Sistemler Elektrik ve Elektronik Teknolojisi",
  "Raylı Sistemler İşletmeciliği",
  "Raylı Sistemler Makine Teknolojisi",
  "Raylı Sistemler Makinistlik",
  "Raylı Sistemler Makinistlik",
  "Raylı Sistemler Mühendisliği",
  "Raylı Sistemler Yol Teknolojisi",
  "Rehberlik ve Psikolojik Danışmanlık",
  "Reklamcılık",
  "Reklamcılık",
  "Rekreasyon",
  "Rus Dili ve Edebiyatı",
  "Rus Dili ve Edebiyatı Öğretmenliği",
  "Saç Bakımı ve Güzellik Hizmetleri",
  "Sağlık Bilgi Sistemleri Teknikerliği",
  "Sağlık Kurumları İşletmeciliği",
  "Sağlık Turizmi İşletmeciliği",
  "Sahne ve Dekor Tasarımı",
  "Sahne ve Gösteri Sanatları Teknolojisi",
  "Sanat Tarihi",
  "Sanat Yönetimi",
  "Seracılık",
  "Seramik Tasarımı",
  "Seramik, Cam ve Çinicilik",
  "Sermaye Piyasası",
  "Seyahat İşletmeciliği",
  "Seyahat İşletmeciliği ve Turizm Rehberliği",
  "Sınıf Öğretmenliği",
  "Sigortacılık",
  "Sigortacılık ve Sosyal Güvenlik",
  "Silah Sanayi Teknikerliği",
  "Sinema ve Televizyon",
  "Sinoloji",
  "Sivil Hava Ulaştırma İşletmeciliği",
  "Sivil Havacılık Kabin Hizmetleri",
  "Sivil Savunma ve İtfaiyecilik",
  "Siyaset Bilimi",
  "Siyaset Bilimi ve Kamu Yönetimi",
  "Siyaset Bilimi ve Uluslararası İlişkiler",
  "Sondaj Teknolojisi",
  "Sosyal Bilgiler Öğretmenliği",
  "Sosyal Güvenlik",
  "Sosyal Hizmetler",
  "Sosyal Hizmetler",
  "Sosyoloji",
  "Spor Bilimleri",
  "Spor Yönetimi",
  "Su Altı Teknolojisi",
  "Su Bilimleri ve Mühendisliği",
  "Su Ürünleri İşleme Teknolojisi",
  "Su Ürünleri Mühendisliği",
  "Sulama Teknolojisi",
  "Sümeroloji",
  "Süryani Dili ve Edebiyatı",
  "Süs Bitkileri Yetiştiriciliği",
  "Süt Teknolojisi",
  "Süt ve Besi Hayvancılığı",
  "Süt ve Ürünleri Teknolojisi",
  "Şarap Üretim Teknolojisi",
  "Şehir ve Bölge Planlama",
  "Tapu Kadastro",
  "Tapu ve Kadastro",
  "Tarım Ekonomisi",
  "Tarım Makineleri",
  "Tarım Makineleri ve Teknolojileri Mühendisliği",
  "Tarımsal Biyoteknoloji",
  "Tarımsal İşletmecilik",
  "Tarımsal Ürünler Muhafaza ve Depolama Teknolojisi",
  "Tarımsal Yapılar ve Sulama",
  "Tarih",
  "Tarih Öğretmenliği",
  "Tarih Öncesi Arkeolojisi",
  "Tarla Bitkileri",
  "Tarla Bitkileri",
  "Taşınabilir Kültür Varlıklarını Koruma ve Onarım",
  "Tekstil Mühendisliği",
  "Tekstil Tasarımı",
  "Tekstil Teknolojisi",
  "Tekstil ve Halı Makineleri",
  "Tekstil ve Moda Tasarımı",
  "Tıbbi Dokümantasyon ve Sekreterlik",
  "Tıbbi Görüntüleme Teknikleri",
  "Tıbbi Laboratuvar Teknikleri",
  "Tıbbi Tanıtım ve Pazarlama",
  "Tıbbi ve Aromatik Bitkiler",
  "Tıp",
  "Tıp Mühendisliği",
  "Tiyatro Eleştirmenliği ve Dramaturji",
  "Tohum Bilimi ve Teknolojisi",
  "Tohumculuk Teknolojisi",
  "Toprak Bilimi ve Bitki Besleme",
  "Turist Rehberliği",
  "Turizm Animasyonu",
  "Turizm İşletmeciliği ve Otelcilik",
  "Turizm ve Otel İşletmeciliği",
  "Turizm ve Seyahat Hizmetleri",
  "Türk Dili ve Edebiyatı",
  "Türk Dili ve Edebiyatı Öğretmenliği",
  "Türk Halkbilimi",
  "Türk İslam Arkeolojisi",
  "Türkçe Öğretmenliği",
  "Türkoloji",
  "Tütün Eksperliği",
  "Uçak Bakım ve Onarım",
  "Uçak Mühendisliği",
  "Uçak Teknolojisi",
  "Uçak ve Uzay Mühendisliği",
  "Ukrayna Dili ve Edebiyatı",
  "Ulaştırma Mühendisliği",
  "Ulaştırma ve Trafik Hizmetleri",
  "Uluslararası İlişkiler",
  "Uluslararası Ticaret ve Finans",
  "Urdu Dili ve Edebiyatı",
  "Uzay Bilimleri ve Teknolojileri",
  "Üç Boyutlu Modelleme ve Animasyon",
  "Üretimde Kalite Kontrol",
  "Veterinerlik",
  "Yaban Hayatı Ekolojisi ve Yönetimi",
  "Yağ Endüstrisi",
  "Yapı Denetimi",
  "Yapı Ressamlığı",
  "Yapı Tesisat Teknolojisi",
  "Yapı Yalıtım Teknolojisi",
  "Yaşlı Bakımı",
  "Yat Kaptanlığı",
  "Yazılım Mühendisliği",
  "Yerel Yönetimler",
  "Yerel Yönetimler",
  "Yiyecek ve İçecek İşletmeciliği",
  "Yunan Dili ve Edebiyatı",
  "Zaza Dili ve Edebiyatı",
  "Zeytincilik ve Zeytin İşleme Teknolojisi",
  "Ziraat Mühendisliği Programları",
  "Zootekni",
];
